### ISSUE TITLE
Events Works on laptop but not on remote server

### ISSUE THREAD

**Issue by bparmind** [bokmann/fullcalendar_assets#1]
Hi BokMann, 

Thank for sharing awesome ruby apps, I had issue with it, the events shows up on my local server i.e on my server but it doesn't shows up when i run it on remote server

Can you help me with this.

Thanks

**Comment by bokmann** [comment]
Issues with your server configuration should not be filed against this gem.  This gem is known to work in production against apache/passenger with both REE and ruby 1.9.2
